### ISSUE TITLE
realtime display

### ISSUE THREAD

**Issue by hive-cas** [NVIDIA/VideoProcessingFramework#102]
This is a wonderful project! Thanks for the contribution to the community!
I have a quick question. My intent is to display the encoded frame (after infer with my custom trained pytorch model) on my monitor. Currently, I just convert the output image tensor to CPU via opencv:

`           out = out.cpu().numpy()
            out_img = cv2.cvtColor(np.asarray(out), cv2.COLOR_RGB2BGR)
            cv2.imshow('Video ', out_img)
`
I see this project could accelerate the decoding/encoding process, but is it possible to speed up the display instead of using opencv imshow which relies on CPU and numpy? In my case, this is the major bottleneck.

**Comment by rarzumanyan** [comment]
Hi @hive-cas
Thank you for the kind talk.

>is it possible to speed up the display instead of using opencv imshow which relies on CPU and numpy?

Nvdec always stores decoded frames in GPU memory (because it's part of GPU chip).
So all the VPF functions which return numpy array do Device to Host CUDA memcpy under the hood.
Given that, technically it's possible to use interoperability between CUDA and OpenGL (or DirectX). However, this will require fair amount of effort.

If there are Python projects which implements such interoperability between CUDA and OpenGL / DirectX you can obtain `CUdeviceptr` of decoded frame the same it's done in `PytorchNvcodecModule` which implements export to Pytorch tensors through plain `CUdeviceptr`.

**Comment by hive-cas** [comment]
Thanks for the feedback! @arzumanyan 
I see. I think for now I can only resort to opencv for display. 
On the other side, the decode process is also done by:
`_ , frame = videoCapture.read()`
`img = Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))`
`image = Variable(ToTensor()(img)).unsqueeze_(0).cuda()`
`output = model(image)`

Do you think, intuitively, it will increase FPS if I use VPF to replace these codes to for decoding?

**Comment by rarzumanyan** [comment]
Hi @hive-cas 

You can replace your OpenCV decode + color conversion calls with `PyNvDecoder` + `PySurfaceConverter` + `PySurfaceDownloader` chain like it's shown in SampleDecodeMultiThread.py:

https://github.com/NVIDIA/VideoProcessingFramework/blob/ff68d9aea2cd82db54bcf1ee68c1685bb0f23c4b/SampleDecodeMultiThread.py#L26-L33

One thing you need to change is the color conversion (RGB instead of YUV420).

>Do you think, intuitively, it will increase FPS if I use VPF to replace these codes for decoding?

Depends on how fast your CPU and GPU are. 
Generally VPF shall be 2x-3x times faster as it uses HW decoder & CUDA for color conversion.

**Comment by hive-cas** [comment]
I have tested the FPS on my Titan V, and it is amazing! Around 2000fps for decoding and color conversion. The only problem is converting the decoded RGB planar to pytorch tensor, issue #105 . 
This issue could be closed. Thanks for the kind reply and great contribution. @rarzumanyan

**Comment by rarzumanyan** [comment]
Great news.
Closing this as fixed.
