### ISSUE TITLE
How to convert a pytorch tensor to surface for downloading from device to host

### ISSUE THREAD

**Issue by hive-cas** [NVIDIA/VideoProcessingFramework#109]
Sorry for the long title..:)
The wiki shows the conversion from surface to tensor. I have manipulated my tensor, and intend to display it. I think the procedure should be : pytorch tensor --> surface --> DownloadSingleSurface. Is there any API for this purpose? 
Currently:

```
out = model(surface_tensor) #surface_tensor is [N,C,H,W]
out = (out[0].permute(1, 2, 0)).to(torch.uint8)#CHW [0,1,2], HWC[1,2,0]
out  =out.cpu().numpy()
out_img = cv2.cvtColor(out, cv2.COLOR_RGB2BGR)
cv2.imshow('test ', out_img)
```

**Comment by rarzumanyan** [comment]
@hive-cas 

There's Pytorch API for downloading CUDA tensor to RAM and converting it to Numpy array, please use that.
You can use e. g. `cpu().numpy()` on your CUDA tensor.

**Comment by hive-cas** [comment]
> @hive-cas
> 
> There's Pytorch API for downloading CUDA tensor to RAM and converting it to Numpy array, please use that.
> You can use e. g. `cpu().numpy()` on your CUDA tensor.

@rarzumanyan 
Does VPF provide a faster way to copy pytorch tensor from device to host? I mean, such .cpu().numpy() thing is really slow (bottleneck that harms fps severely)...

**Comment by rarzumanyan** [comment]
>I mean, such .cpu().numpy() thing is really slow (bottleneck that harms fps severely)

I didn't compare the performance between VPF `PySurfaceDownloader` and Pytorch `tensor.cpu().numpy()`. VPF may be just as slow. If you have a performance result to compare - could you please provide them? That would be very useful.

>Does VPF provide a faster way to copy pytorch tensor from device to host?

No, it doesn't. 
Reason is simple - Torch is big framework with variety of CUDA tensor formats and comprehensive C++ API.
I'm not profound in Torch C++ API enough to implement this in reasonable amount of time (wasted ~2 weeks of trial and error to find out that Torch prefers RGB tensors in planar format).

Since this is open-source project I hope that maybe someone with enough spare time & expertise in Torch will add this feature :)
