### ISSUE TITLE
Windows: ImportError DLL Load failed: Procedure not found

### ISSUE THREAD

**Issue by 0xprincess** [NVIDIA/VideoProcessingFramework#121]
**Describe the bug**
After successful build in Windows 10 environment (MSVC19, cuda10.2, anaconda), there's an error when trying to import PyNvCodec

``` 
Traceback (most recent call last):
  File "SampleDecode.py", line 16, in <module>
    import PyNvCodec as nvc
ImportError: DLL load failed: procedure not found
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - nvidia driver version 456.38
 - cuda version 10.2
 - Video Codec SDK Version 10.0.26
 - Python Version 3.7

**Additional context**
Also I made a build using cuda10.1, and the same error happened.
All builds was made using ffmpeg from https://www.gyan.dev/ffmpeg/builds/ (the link is posted on official ffmpeg website), because Zeranoe FFMpeg doesn't available anymore.

**Comment by rarzumanyan** [comment]
Hi @SebyakinAndrei 

>ImportError: DLL load failed: procedure not found

This error means some of DLLs which PyNvCodec.pyd is linked against are missing. 
You can investigate using procmon tool like it's described [here](https://www.codeproject.com/articles/560816/troubleshooting-dependency-resolution-problems-usi). Before delving into this I recommend you to do the following:

1. Put FFmpeg DLLs into VPF installation folder (e. g. on my machine it's `C:\GitHub\VideoProcessingFramework\install\bin`)
2. Navigate to VPF installation folder and run one of the samples in cmd shell from there.

E. g. on my machine in the VPF installation directory I have following files:
```cmd
 Directory of C:\GitHub\VideoProcessingFramework\install\bin

10/12/2020  09:19 PM    <DIR>          .
10/12/2020  09:19 PM    <DIR>          ..
12/25/2019  02:43 PM        44,483,072 avcodec-58.dll
12/25/2019  02:43 PM        10,393,088 avformat-58.dll
12/25/2019  02:43 PM           883,712 avutil-56.dll
12/19/2017  05:40 PM       725,106,140 big_buck_bunny_1080p_h264.mov
10/12/2020  08:13 PM           838,144 PyNvCodec.cp37-win_amd64.pyd
10/12/2020  08:44 PM           146,944 PytorchNvCodec.cp37-win_amd64.pyd
10/12/2020  09:18 PM             2,118 SampleDecode.py
08/27/2020  02:50 PM             3,652 SampleDecodeMultiThread.py
06/29/2020  09:56 AM             2,115 SampleDecodeSw.py
10/06/2020  11:18 AM             2,946 SampleEncode.py
04/30/2020  10:47 AM             3,859 SampleEncodeMultiThread.py
12/25/2019  02:43 PM           428,544 swresample-3.dll
10/12/2020  03:46 PM           403,968 TC.dll
09/24/2020  02:39 PM            43,008 TC_CORE.dll
```

Then you can run one of the samples:
```cmd
cd C:\GitHub\VideoProcessingFramework\install\bin
python SampleDecode.py 0 big_buck_bunny_1080p_h264.mov big_buck_bunny.yuv
```

And check the content of raw NV12 video file `big_buck_bunny.yuv` using one of the raw video players (YUV Player works fine under Windows).

**Comment by SebyakinAndrei** [comment]
Thank you for your reply!
The error persists even after putting ffmpeg libs to vpf folder, so I'll try to investigate the issue with method your linked.
But what I can't understand is that how vpf successfully builds with this libraries missed. Shouldn't it fail the compilation during linking?

**Comment by rarzumanyan** [comment]
>Shouldn't it fail the compilation during linking?

**Comment by SebyakinAndrei** [comment]
I followed the guide and i've got too many output lines, so to filter it out and understand, what dll's it cannot resolve, it dumped it to csv file, previously filtered by process and  and wrote a simple python script:
```python
import pandas as pd 

df = pd.read_csv('E:\\VideoProcessingFramework\\Logfile.csv')
df['Lib'] = list(map(lambda s: s[s.rfind('\\') + 1:], df['Path'].values))
a = set(map(lambda s: s.lower(), df[df['Result'] == 'SUCCESS']['Lib'].values))
b = set(map(lambda s: s.lower(), df['Lib'].values))
print(len(a), len(b), b.difference(a))
```
And the result i've got is the all dll was resolved eventually, since the difference was zero.
So in procmon, is swithed off filter by result type and found suspicious event with result BUFFER OVERFLOW that happend right in python.exe process near the process exit. I went to Event Properties window and in Process tab, all dll's seems to loaded successfully. I can't extract more useful information from Stack tab, because I don't have a qualification to understand a bit.
[LogfileFull.zip](https://github.com/NVIDIA/VideoProcessingFramework/files/5377851/LogfileFull.zip)
I uploaded procmon logfile, filtered by process and hope you can help me to figure out what happened, because I can't figure out what I'm doing wrong that causes vpf to crash.
