### ISSUE TITLE
what is that ‘Make sure you link VPF against desired ffmpeg version.’

### ISSUE THREAD

**Issue by ltm920716** [NVIDIA/VideoProcessingFramework#149]
**Describe the bug**
Make sure you link VPF against desired ffmpeg version.

hello，
     I want to know the matching version between vpf and ffmpeg

**Comment by rarzumanyan** [comment]
Hi @ltm920716 

>I want to know the matching version between vpf and ffmpeg

There's no such thing as ffmpeg version matching for ffmpeg. 
Latest version is recommended but any reasonably recent version will do. 

>Make sure you link VPF against desired ffmpeg version.

This kind of situation often happens when user has multiple ffmpeg versions across the system and VPF was linked against one of them while it loads another at runtime. It's not related to any particular ffmpeg release.
