### ISSUE TITLE
How to give encoded frame to VPF from python?

### ISSUE THREAD

**Issue by sayanmutd** [NVIDIA/VideoProcessingFramework#151]
How do i give encoded frame (i.e encoded h264 or h265 frame) to VPF using python?
Is there any kind of function call like DecodeSingleFrame, which takes encoded buffer and gives decoded surface from python.

**Comment by rarzumanyan** [comment]
>Is there any kind of function call like DecodeSingleFrame, which takes encoded buffer and gives decoded surface from python.

This topic is covered by `SampleDemuxDecode.py`:
https://github.com/NVIDIA/VideoProcessingFramework/blob/38b9953840be8b7b97330117d49f3e682d171c28/SampleDemuxDecode.py#L30-L41

Instead of demuxing packet with built-in demuxer you can provide it from any other source in form of numpy array.
Please not that incoming packet shall be valid Annex.B NAL Unit (this is the format expected by Nvidia HW).
