### ISSUE TITLE
How to get surface containing floating point numbers

### ISSUE THREAD

**Issue by vtpl1** [NVIDIA/VideoProcessingFramework#169]
Hi,
Is there a way to get floating point RGB PLANAR surface?
Is there any surface converter or any mechanism which can be used to convert uint8 surface and normalize it (divide by 255.0) to give float32 result?

RGB_PLANAR (uint8) surface -> RGB_PLANAR (float32) surface

**Comment by rarzumanyan** [comment]
Hi @vtpl1 

If you need to convert RGB_PLANAR `Surface` from uint8 to float32 for further export to PyTorch tensor, this topic is covered [here](https://github.com/NVIDIA/VideoProcessingFramework/wiki/Exporting-video-frame-to-Pytorch-tensor).
Otherwise if you just need to convert from RGB_PLANAR uint8 `Surface` to RGB_PLANAR float32 `Surface` and use it inside VPF, this isn't yet supported.

**Comment by rarzumanyan** [comment]
@vtpl1 

Please take a look at pull request #184.
It adds RGB U8 -> RG F32 conversion support but just needs some attention (CUDA kernels need to be replaced with NPP).

**Comment by contentis** [comment]
Can this be closed?
