### ISSUE TITLE
example of DataProvider

### ISSUE THREAD

**Issue by vtpl1** [NVIDIA/VideoProcessingFramework#181]
Hi @rarzumanyan ,

Is there any example use of the `DataProvider`?
I want to feed the demuxer separately from a custom data source. 

https://github.com/NVIDIA/VideoProcessingFramework/blob/9bc26376ef73835a1ca91f1c43bd99cd9d77579b/PyNvCodec/TC/src/FFmpegDemuxer.cpp#L53-L57

**Comment by rarzumanyan** [comment]
Hi @vtpl1 

Unfortunately I don’t have any examples on this topic because it’s difficult to map such a class between C++ land and Python buffered readers.

If you’re using C++ only it shall be easier because this DataProvider class is basically a shim class. There are some code samples about buffered readers for AVFormatContext class, my advice is to follow them.

**Comment by vtpl1** [comment]
Ok,
Thank you Roman.
