### ISSUE TITLE
Multi GPU decoder performance

### ISSUE THREAD

**Issue by vtpl1** [NVIDIA/VideoProcessingFramework#182]
Hi @rarzumanyan ,
When I am trying to decode in multiple GPUs the FPS is getting devided by number of GPUs.
While running in Multi GPU the decoder  (`nvidia-smi dmon`) remains 10 - 12% loaded and CPU is sufficiently free.
The test case involve only decoding from h264 to nv12 surface no further processing and CPU transfers are done.

But when I am running multiple thread in single GPU the FPS is pretty high.

I am suspecting a global lock while running in multiple GPU.

Can you give me some hint?

**Comment by vtpl1** [comment]
@rarzumanyan , this issue is not specific to python, c++ API also has the same behavior.

**Comment by vtpl1** [comment]
Hi @rarzumanyan,

Do we really need to create a memory and copy the memory supplied using:

`Buffer::MakeOwnMem(pPacket->size(), pPacket->data())); ` this is degrading the performance heavily. Can we not use `Buffer::Make(pPacket->size(), (void *)pPacket->data())); ` 

https://github.com/NVIDIA/VideoProcessingFramework/blob/9bc26376ef73835a1ca91f1c43bd99cd9d77579b/PyNvCodec/src/PyNvCodec.cpp#L492-L522

**Comment by rarzumanyan** [comment]
Hi @vtpl1 

```cpp
Buffer::Make(pPacket->size(), (void *)pPacket->data()));
```
Will use the data supplied to C++ land from Python land.

Memory allocation referenced by this ptr goes all the way through VPF to `cuvidParseVideoData` Video Codec SDK call so if data changes in between the moment it's passed to C++ and the moment buffer is kicked of to HW it may cause errors which are very hard to track.

>this is degrading the performance heavily

Do you have a numbers on how badly does it hurt the performance?

P. S.
BTW did you have a chance to look at issue #188 ?
I'd really like to solve the issues one by one instead of taking up multiple at once.

**Comment by rarzumanyan** [comment]
Hi @vtpl1 

Please check out `gil_release_support` branch, it adds Python GIL release to `PyNvEncoder::EncodeSingleSurface` and `PyNvDecoder::DecodeSurface` methods.

With latest changes I see higher decoder usage on RTX5000 which has 2 Nvdec units. `SampleDecodeMultiThread` shows ~80% of Nvdec occupancy.
