### ISSUE TITLE
RTSP stream stuck

### ISSUE THREAD

**Issue by Sayyam-Jain** [NVIDIA/VideoProcessingFramework#197]
Hi, I was testing the RTSP stream which worked very well. (SampleDecode.py)
However, once the RTSP link goes dead (pulled Ethernet Cable manually for testing before deploying it), whole python code gets stuck and no line executes (even independent threads stop working and doesn't ever come back up.

From testing, I found that this line is the main culprit:
`rawSurface = self.nvDec.DecodeSingleSurface()`

P.S. I'd use ffmpeg with hw accelaration for decoding, but running it in subprocess consumes a high CPU usage, especially when trying to run multiple streams in python (streams > 8), plus I need to resize the frame on GPU to save CPU cycles.

Can you please help.
Thanks

**Comment by rarzumanyan** [comment]
Hi @Sayyam-Jain 

`PyNvDecoder` class uses built-in demuxer (`PyFFMpegDemuxer` class) which relies on ffmpeg C API by default.
As you pull out Ethernet cable, `PyNvDecoder::DecodeSingleSurface()` method stucks because it can no longer connect to RTSP camera and demuxer (which maintains RTSP connection and extract Annex.B NAL units for HW decoder) never returns.

To prevent this I recommend you to use stand-alone demuxer as it's shown [here](https://github.com/NVIDIA/VideoProcessingFramework/wiki/Decoding-video-from-RTSP-camera).

>even independent threads stop working and doesn't ever come back up

I assume this happens because of Python GIL.
Please check out #182, GIL release was implemented in that branch and I'm basically waiting for issue originator to test my fix. If you confirm that it fixes multi-thread issue, I'll merge the patch to master branch.

**Comment by Sayyam-Jain** [comment]
I apologise for such a late reply. 
Thank you for your help. The `gil_release_support` branch fix **works**. I'm planning to run pynvcodec in separate thread and stop it if it gets stuck. 
Thanks again for your help. I'll close the issue now
