### ISSUE TITLE
FlushSinglePacket() returns all the encoded packets together.

### ISSUE THREAD

**Issue by lferraz** [NVIDIA/VideoProcessingFramework#200]
**Describe the bug**
Previously FlushSinglePacket() was returning encoded packets one by one, now they are returned together (the same as using Flush()).

I tried to debug the code but I couldn't see where is the problem.

**Expected behavior**
FlushSinglePacket() should return encoded packets one by one

**Comment by rarzumanyan** [comment]
Hi @lferraz 

This behavior was caused by typo in `EncodeContext` constructor:
https://github.com/NVIDIA/VideoProcessingFramework/blob/b138cc89dd25ad1751105dce6e0f9d689f539b78/PyNvCodec/src/PyNvCodec.cpp#L1304-L1309

It was called with `is_append` flag set as `true`:
https://github.com/NVIDIA/VideoProcessingFramework/blob/b138cc89dd25ad1751105dce6e0f9d689f539b78/PyNvCodec/inc/PyNvCodec.hpp#L285-L288

In combination with encoded packet not being cleared before `FlushSinglePacket` call.
So encoded packet obtained after `FlushSinglePacket` was appended to output.
Please check out `issue_200` ToT. It's based on `master`, not `issue_195`.

P. S.
Could you please confirm that #195 is resolved so that I can merge it with master?

**Comment by lferraz** [comment]
hi @rarzumanyan, 

thank you so much for this very fast solution.
I have in mind to check #195 this afternoon or tomorrow morning. I was quite busy integrating VPF and I couldn't do it earlier, sorry.

**Comment by rarzumanyan** [comment]
Thanks for the update @lferraz 

NP with that, I'll wait till you're done with #195 and merge it later. 
Since #195 patch is huge I'd really like to merge it with master in fast-forward mode and then add couple smaller fixes from other branches over the top of it.

**Comment by lferraz** [comment]
Hi @rarzumanyan ,

I already tested `issue_200` and works great!!! 🎉
This afternoon I will test #195 with VideoCodec SDK 10. I cannot test it with 11 in an easy way. Sorry.
