### ISSUE TITLE
CUDA not included in CMake and VisualStudio Projects

### ISSUE THREAD

**Issue by shuoxinma4** [NVIDIA/VideoProcessingFramework#240]
CMake Not producing CUDA FLAGS, "CUDA C/C++" and "CUDA Linker" tabs missing in Visual Studio Project Property, CUDA headers and libs not included in projects

**To Reproduce**
Cmake configure&generate and launch Visual studio project

**Expected behavior**
In previous versions, after CMake configure, there are several CMAKE_CUDA_* flags, and the generated Visual Studio projects correctly include CUDA headers and libs. (One I pulled on Mar. 16, the other on July 26)

**Screenshots**
---

**Desktop (please complete the following information):**
 - OS: Windows 10.0.19043
 - Nvidia driver version: 471.96
 - CUDA Version: 11.1
 - Video Codec SDK Version: 11.1.5
 - Python Version: 3.7
 - Visual Studio: Community 2019 - 16.8.4

**Additional context**

**Comment by rarzumanyan** [comment]
Hi @shuoxinma4 

This is caused by changes in CMake file done by commit #80838ce9b26ae00c84f93c28137938b3d3de31ad:
![image](https://user-images.githubusercontent.com/45193474/133398252-172f58e5-885e-40a0-b133-eeb1da8e89ce.png)

It doesn't reproduce under Linux and looks like it doesn't _always_ reproduce under Windows. I'll put back the `enable_language(CUDA)` and will update you in this thread.

**Comment by rarzumanyan** [comment]
@shuoxinma4 

Please check `master` ToT and confirm if the problem is solved.

**Comment by shuoxinma4** [comment]
Its up and running again!
Thank you.
