### ISSUE TITLE
Example for a simple pipeline

### ISSUE THREAD

**Issue by Feri73** [NVIDIA/VideoProcessingFramework#252]
I want to read all frames of a video into memory as an rgb numpy array, process it, and write it back to the disk as a video, but I am unable to figure out how to use this tool for that. Is there any example or guideline anywhere that can help me find out the most efficient way to do this using VPF? I know that I can read frames into surfaces, convert them to rgb, and download them one by one, but I am not sure if this is the most efficient way to do this.
Thank you.

**Comment by rarzumanyan** [comment]
Hi @Feri73 

>I am unable to figure out how to use this tool for that.

>I know that I can read frames into surfaces, convert them to rgb, and download them one by one, but I am not sure if this is the most efficient way to do this.

Assuming this issue is a best practice request.

Long story short, the most efficient way to use GPU to process video frames is to decode it with Nvdec and keep it in CUDA memory using `Surface` class. Performance is very broad term, it can be different, like:

- Highest throughput: process as many frames as possible in shortest amount of time.
- Lowest latency: decode and process frames with minimal amount of time between decode start and processing finish.
- Energy saving: keep as much on GPU as possible because typically GPUs are more energy efficient processing videos and images rather then CPUs.
- HW enabling: you've payed $$$ for the whole GPU and want to use it all by utilizing Nvdec / Nvenc / Cuda cores / TensorRT cores.

The most efficient way to use VPF is to keep everything on GPU if possible: decoding, color conversion, encoding. VPF supports handshake with other frameworks such as `pycuda`, `torch`, `tensorrt`, `opencv`, `numpy` and such to avoid unneccessary data copies: you can decode and process your video frames, then feed it to ML framework, then convert it back to nv12 / yuv444 and encode for storage without leaving vRAM.

There's bunch of python samples which illustrate all of VPF features, so please go through them to make yourself more familiar with it's interface. Whole VPF interface is declared in single C++ file (PyNvCodec/src/PyNvCodec.cpp) which exports C++ libraries to Python land:
https://github.com/NVIDIA/VideoProcessingFramework/blob/fad275347e24f017b9c4aec796806aa0a124b846/PyNvCodec/src/PyNvCodec.cpp#L1663-L1665
