### ISSUE TITLE
Question about DecodeFrameFromPacket, opencv

### ISSUE THREAD

**Issue by acschristoph** [NVIDIA/VideoProcessingFramework#269]
Hi,

I use DecodeFrameFromPacket because a have a rtp client that dumps it to a annex b
after DecodeFrameFromPacket I want to display the frame with open cv I have looked into samples,
but form me it is not clear, how todo this.

Is there an documentation out there or can u give me please a hint.

thank you

**Comment by rarzumanyan** [comment]
Hi @acschristoph 

Since VPF can export save video frames to numpy arrays, the procedure is same as usual, you simply export your numpy array to OpenCV image and show it.

It can be done like this (reusing code from `SampleDemuxDecode.py`):
```python
#Get raw dimensions of YUV420 frame
raw_w, raw_h = nvDmx.Width(), int(nvDmx.Height() * 3 / 2)

surface_nv12 = nvDec.DecodeSurfaceFromPacket(pdata, packet)
if not surface_nv12.Empty():
    # Convert to YUV420 as usual
    surface_yuv420 = nvCvt.Execute(surface_nv12, cc_ctx)
    if surface_yuv420.Empty():
        break
    if not nvDwn.DownloadSingleSurface(surface_yuv420, rawFrame):
        break

    #Reshape numpy array because right now it's a 1d chunk of memory
    rawFrame = rawFrame.reshape((raw_h, raw_w))

    #Convert to BGR which is native OpenCV color space
    yuv420_mat = cv2.cvtColor(rawFrame, cv2.COLOR_YUV2BGR_I420)

    #Show in window
    cv2.imshow("Decoded frame", yuv420_mat)
    cv2.waitKey()
```

Produces an output like this:
![image](https://user-images.githubusercontent.com/45193474/139654670-d18dd5c5-6ea5-4a14-9d9d-373ff1f2ded4.png)
