### ISSUE TITLE
Triton Integration

### ISSUE THREAD

**Issue by dbasbabasi** [NVIDIA/VideoProcessingFramework#290]
Hi!

I see, you have a task ongoing for **triton inference server integration**. When do you plan to integrate with it? In this ecosystem, rtsp decoding is a big problem. There is almost no package to decode such streams on camera using gpu except gstreamer and vpf. We faced several bugs brought by different encodings and threading system in GStreamer.

I’d be more than happy if you have a solution on how to use vpf with triton

Thanks for your help!

**Comment by rarzumanyan** [comment]
Hi @dbasbabasi 
Could you please give more information about your use case? Do you use Triton remotely or on the same machine as VPF?

E. g. issue #207 is related to better interoperability between VPF and Triton when both are used on the same machine.
Otherwise, if you send the data to Triton server over the network there's not too much room for optimization, one has to copy data from vRAM to RAM in order to have it sent over network.

**Comment by contentis** [comment]
This is being tracked in #207, going to close.
