### ISSUE TITLE
About cpp syntax

### ISSUE THREAD

**Issue by pdd-999** [NVIDIA/VideoProcessingFramework#308]
Pretty new to C++. How should I interpret this piece of code:

https://github.com/NVIDIA/VideoProcessingFramework/blob/ec453adcb2c3cd5cd566300d613d3ffd63343dda/PyNvCodec/src/PyNvDecoder.cpp#L660-L671

**Comment by rarzumanyan** [comment]
Hi @pdd-999 

I've edited your comment slightly and replaced code snippet with permalink. 

Basically, this piece of code is a place where C++ class method is exported to Python land with help of pybind11.
Suppose you have your Python code similar to this:

```python
import PyNvCodec as nvc

gpu_id = 0
nvdec = nvc.PyNvDecoder("input.mp4", gpu_id)

pdata = nvc.PacketData()
dec_surf = nvdec.DecodeSingleSurface(pdata)
```

As you call the `DecodeSingleSurface` method, the control flow will finally jump from Python interpreter into C++ library. It happens because VPF core is written in C++ and only high-level classes are exported to Python module.

At the line 662 we have a C++ lambda function. It's first argument is the pointer to the `PyNvDecoder` class instance. This class incapsulates everything lower level and it corresponds to `nvc.PyNvDecoder` in your Python code. Second argument is a reference to `PacketData` structure which stores information like timestamp, packet size and such.

Within this lambda function, `DecodeContext` structure is instantiated which serves as entry point to C++ interface of `PyNvDecoder` class. You see plenty of `DecodeSingleSurface` function implementations, so to avoid a massive overload at C++ side, different `DecodeContext` constructors are called instead.

The rest is more self-expanatory: If `DecodeSurface` method succeed, the pointer to decoded surface will be returned back to Python interpreter. Otherwise, empty surface class will be instantiated and returned to Python interpreter instead.

**Comment by pdd-999** [comment]
@rarzumanyan I have some more questions:
 1. https://github.com/NVIDIA/VideoProcessingFramework/blob/ec453adcb2c3cd5cd566300d613d3ffd63343dda/PyNvCodec/TC/inc/NvDecoder.h#L111-L114
I can see that the function `HandlePictureDisplayProc` takes a void pointer and a 
`CUVIDPARSERDISPINFO` pointer as input. About the output, does `((NvDecoder *)pUserData)` just cast a void pointer to a `NvDecoder` pointer? If yes, how do you know that `pUserData` can be casted to `NvDecoder`?

2. https://github.com/NVIDIA/VideoProcessingFramework/blob/ec453adcb2c3cd5cd566300d613d3ffd63343dda/PyNvCodec/TC/src/NvDecoder.cpp#L613-L639
I can see that you are creating a `CUVIDPARSERPARAMS` struct and passing it to `cuvidCreateVideoParser`. Is the implementation of the function `cuvidCreateVideoParser` closed source?

**Comment by rarzumanyan** [comment]
Hi @pdd-999 

>If yes, how do you know that pUserData can be casted to NvDecoder?

Allow me to start with a bit more general explanation first.

Video stream consists of NAL Units, each of which either stores encoded frames or contains other useful information such as profile, tier, level, resolution, color bit depth and such. In order to parse this information, Annex.B elementary parser is used which (re)configures decoder. 

Video Codec SDK has a built-in parser which (re)configures decoder on the fly as it takes Annex.B NAL units from video stream.

Long story short, this built-in parser allows user to register 3 callbacks:

- `pfnSequenceCallback` which will be called upon decoder (re)configure.
- `pfnDecodePicture` which will be called every time encoded video frames is sent to Nvdec.
- `pfnDisplayPicture` which will be called every time the decoder has reconstructed video frame and can return it to user.

https://github.com/NVIDIA/VideoProcessingFramework/blob/ec453adcb2c3cd5cd566300d613d3ffd63343dda/PyNvCodec/TC/src/NvDecoder.cpp#L633-L635

This is the signature of `pfnDisplayPicture` callback:
```cpp
typedef int (CUDAAPI *PFNVIDDISPLAYCALLBACK)(void *, CUVIDPARSERDISPINFO *);
```

And this is the signature of `HandlePictureDisplayProc` function we register as callback:
https://github.com/NVIDIA/VideoProcessingFramework/blob/ec453adcb2c3cd5cd566300d613d3ffd63343dda/PyNvCodec/TC/inc/NvDecoder.h#L111-L114

So we now for sure we can cast `void*` to `NvDecoder*` just because we did it all ourselves.

>Is the implementation of the function cuvidCreateVideoParser closed source?

Yes, this function is implemented within Video Codec SDK runtime libraries which are part of the GPU driver distributive.

It's also possible to create your own Annex.B parser and use it instead of built-in Video Codec SDK parser. It's not an easy job, but you can see how it's done in FFMpeg library. If you launch it like this:
```
ffmpeg -hwaccel cuda -hwaccel_output_format cuda -i video.mp4 -f null -y /dev/null
```

It will use Annex.B parser developed by community which is open source and doesn't belong to Video Codec SDK.

**Comment by rarzumanyan** [comment]
@pdd-999 

Is the issue resolved?

**Comment by pdd-999** [comment]
@rarzumanyan yes, it is. Thank you for your prompt reply.

**Comment by rarzumanyan** [comment]
Closing as fixed.
