### ISSUE TITLE
A way to encode/decode clips to/from Surface

### ISSUE THREAD

**Issue by ilia-chelak** [NVIDIA/VideoProcessingFramework#330]
Hello, thanks for the great repo!

I was wondering if there is a way to keep encoded/decoded data on GPU as a `Surface`? In the project I work on, a pre-loaded short clip (e.g., 8 frames) has to go through the following pipeline: Torch tensor -> VPF GPU encoder -> host -> VPF GPU decoder -> Torch tensor. Naturally, IO operations to/from host take a lot of time in comparison with encoding/decoding speed on GPU and are the bottleneck of the application. Therefore, it would be great to get rid of this unnecessary data copying to/from host.

My use case is quite narrow but maybe there is a way? As I understand, ffmpeg has an option `-hwaccel_output_format cuda` to keep its output on cuda, although I don't know how this data can be accessed. So probably there should be some way to keep the decoded/encoded data as a `Surface`. Sorry if I am being mistaken, I am new to video processing.

**Comment by rarzumanyan** [comment]
Hi @ilia-chelak 

> was wondering if there is a way to keep encoded/decoded data on GPU as a Surface?

It's possible to keep decoded video frames in vRAM by using `DecodeSingleSurface` methods of `PyNvDecoder` class.

>Torch tensor -> VPF GPU encoder -> host -> VPF GPU decoder -> Torch tensor.

You would still have to copy encoded video frames from Device to Host and back because `PyNvDecoder` can only accept compressed video frames as numpy arrays. This is by Video Codec SDK design. Fortunately, compressed video frames are very small, usually a matter of kb.

**Comment by ilia-chelak** [comment]
@rarzumanyan 

I see, thank you for the explanation. I will try it out.
