### ISSUE TITLE
Does VPF have a method to skip a frame from video stream? 

### ISSUE THREAD

**Issue by Airuio** [NVIDIA/VideoProcessingFramework#347]
In opencv,  if i want to skip a useless frame for me,  `cap.grab()` could be used, and will be faster than read every frame.
So,  does VPF got method to skip a frame from video stream? 

Specially, if some one wants to gap N frame( or surface), after every time him really decode a surface. 
How can VPF make it faster in this situation?

**Comment by rarzumanyan** [comment]
Hi @Airuio 

You can ignore the frame returned by `PyNvDecoder.DecodeSingleSurface` or use `PyNvDecoder.Seek` to seek for particular frame.

If you need to skip small amount of frames fastest option is to ignore decoded frames.

**Comment by rarzumanyan** [comment]
Closing this issue as resolved.

**Comment by Airuio** [comment]
Thanks, This project is fantastic.
And here is some test as you said( as i understand ^_^):
`###### Decode All frame : Takes 8.02s
while True:
    rawSurface = nvDec.DecodeSingleSurface()
    if rawSurface.Empty():
        break       
    rgb24 = to_rgb.Execute(rawSurface, cc1)
    rgb24.PlanePtr().Export(surface_tensor.data_ptr(), w * 3, gpuID)`

`###### Decode 1/4 of frame and discard 3/4 of them, it takes 7.8s
while True:
    for i in range(4):
        rawSurface = nvDec.DecodeSingleSurface()
    if rawSurface.Empty():
        break       
    rgb24 = to_rgb.Execute(rawSurface, cc1)
    rgb24.PlanePtr().Export(surface_tensor.data_ptr(), w * 3, gpuID)`

Takes almost same time, i hope the second demo should takes less time with suitable funtion of VPF

Eg in opencv：
`#Decode all：Takes 28s
while ret:
    ret,f = cap.read()`

But：
`#Decode 1/4 Only takes 8s
while ret:
    for i in range(4):
        cap.grab()
    ret,f = cap.read()`
The speed is almost 3times。。。

Dose VPF have some method to achieve result like that？ Thank you so much.

**Comment by rarzumanyan** [comment]
Hi @Airuio 

>Decode All frame : Takes 8.02s
>Decode 1/4 of frame and discard 3/4 of them, it takes 7.8s

These are perfectly sane results.
In both cases ALL video frames are decoded but in second case 3/4 of color conversions and exports to tensor are omitted. 
This saves you 0.22s.

>I hope the second demo should takes less time with suitable function of VPF

Honestly I don't know the difference between the `cap.read()` and `cap.grab()`. Also, the structure of your input video file is very important.

If your input video is encoded using "regular" encoder settings, there are data dependencies between video frames. E. g. frame #N may use frames #N-1 and #N-2 as reference (due to small difference between frames each consecutive frame will only store difference between it and it's predecessors). In such case you can't simply jump between frames and you have to decode them all.

Alternatively, your input video may be encoded without inter-frame dependencies. In such case you can actually skip the decode of non-desired frames because it will not interfere the desired frames decoding.

**Comment by Airuio** [comment]
The video we want to deal with is record by ffmpeg in H.264 format, like XXX.ts. (If need, i'd like to offer more information about video format after discuss with my colleague, this all i know now. )

As i understand:
defination of cap"
`cap = cv2.VideoCapture(filePath)`
`cap.grab()` means skip this frame and point to next one without decode it.
`cap.read()` means decode this frame and point to next one.

Dose this video format have suitable api to achieve result like `cap.grab()`?

**Comment by rarzumanyan** [comment]
>The video we want to deal with is record by ffmpeg in H.264 format, like XXX.ts

H.264 is one of the most popular video codecs which supports variety of encoding settings such as:

- All-Intra: all video frames will be encoded as key frames. In this scenario there's no data dependencies between frames.
- Low delay: only I (key) and P (uni-directional prediction) frames will be used. In this scenario there are inter-frame dependencies.
- Latency tolerant: I, P and B (bi-directional prediction) frames will be used. In this scenario there are dependencies between frames and frames reordering.

You can find better description here: [in this Wiki article](https://en.wikipedia.org/wiki/Group_of_pictures).
VPF supports all mentioned settings but only all-intra will allow you to jump between frames without decoding all of them.

If you struggle to determine what's your input, you can contact me via my work email which is mentioned in GitHub profile.

**Comment by Airuio** [comment]
> VPF supports all mentioned settings but only all-intra will allow you to jump between frames without decoding all of them.

Dose VPF have some documentation to help me achieve that? Thank you!

I have send email with a demo video to your work email.
Opencv could accelerate 3 times with `cap.grab()`, and achieve some speed with my 2080Ti GPU in this video format，Thus ， I still think it is possible to accelerate with VPF ^_^. What i need to do is found the right way in VPF.

**Comment by rarzumanyan** [comment]
@Airuio 

>Does VPF have some documentation to help me achieve that? Thank you!

VPF does have the documentation which you can build locally, it's stored in `docs` folder. However it only covers VPF API.
Some general outlook in video coding area is required to develop efficient applications. It's not about the VPF since it's only a tool which allows user to deal with compressed videos from python.

>I have send email with a demo video to your work email.

Thanks, I've received the email.
Your input video has usual GOP structure of I frames followed by number of P frames. Hence there are inter-frame dependencies. 

>OpenCV could accelerate 3 times with `cap.grab()`

I honestly don't know how does OpenCV skip frames without actual decoding while avoiding visual artifacts but just in case I recommend you to inspect decoded frames visually.

>What i need to do is found the right way in VPF.

You can separate the demuxing and decoding process as it's illustrated in `SampleDemuxDecode.py`. 
Following this approach you will first extract compressed video frames from container without actual decode. At this step you can skip encoded frames very quickly. However you may run into all sorts of issues due to unsatisfied inter-frame dependencies. **If you decide to do so, please notice that I won't help you to fix broken frames or decoder exceptions.**

**Comment by Airuio** [comment]
> You can separate the demuxing and decoding process as it's illustrated in SampleDemuxDecode.py
Yes, I have did. And as you said, there were  broken frames comes, and i couldn't found way to solve this problem due to separate the demuxing (and skip frames in demuxinh) and decoding process. Is there Any possible to solve this problem? It would be times faster if we can solve this. Thanks!
