### ISSUE TITLE
How to extact only i frames with VPF

### ISSUE THREAD

**Issue by XuJing98** [NVIDIA/VideoProcessingFramework#356]
For a video, there are three different types of frames that are i frame, b frame, and p frame. So, I'm trying to extract only i frames with VPF to accelerate the video decoding process. And I found FFmpeg supports extracting only  i frames and discarding both b and p frames with -skip_frame 24, for example, the command is: 

```
ffmpeg -skip_frame 24 -i test.mp4 -vsync vfr -frame_pts true out-%02d.jpeg
```
This skip_frame would set **AVCodecContext::skip_frame** to 24 and somehow FFmpeg would discard all the frames except i frames, but I have no idea how to do it with VPF. If I want to add this skip_frame feature to PyNvDecoder class, could you please give me some advice for that? Thank you very much!

**Comment by rarzumanyan** [comment]
Hi @XuJing98 

>This skip_frame would set AVCodecContext::skip_frame to 24 and somehow FFmpeg would discard all the frames except i frames

Just to make it clear, this will only achieve your goal if input video has GOP size equal to 24 and has no forced IDR frames (e. g. inserted due to scene change).

>So, I'm trying to extract only i frames with VPF to accelerate the video decoding process

Perf. optimization is very interesting procedure which is IMO kinda small investigation in a field of computer science.
Allow me to start with the premise evaluation, because false premise can lead to arbitrary consequence.
What's the current problem statement?

1. Codec
2. Resolution
3. Video card
4. `nvidia-smi -dmon` readings

**Comment by XuJing98** [comment]
Sorry, for the confusion, to make it clear, 24 is not about skiping 24 frames, is the value of nointra. (skip all frames except i frames)
<img width="803" alt="截屏2022-07-18 17 02 29" src="https://user-images.githubusercontent.com/53262417/179478665-1307c7a7-3db4-4e36-8411-e6bf2d6984ba.png">
And the command line should be euqual to 
```
ffmpeg -skip_frame nointra -i test2.mp4 -vsync vfr  ./images/%03d.jpeg
```

For a long video, it has so many frames that would spend a lot of time to decode all of them even using gpu, so I'm wondering if I can discard all frames except key frames(i frames) with vpf to accelerate the encoding process.  

> Hi @XuJing98
> 
> > This skip_frame would set AVCodecContext::skip_frame to 24 and somehow FFmpeg would discard all the frames except i frames
> 
> Just to make it clear, this will only achieve your goal if input video has GOP size equal to 24 and has no forced IDR frames (e. g. inserted due to scene change).
> 
> > So, I'm trying to extract only i frames with VPF to accelerate the video decoding process
> 
> Perf. optimization is very interesting procedure which is IMO kinda small investigation in a field of computer science. Allow me to start with the premise evaluation, because false premise can lead to arbitrary consequence. What's the current problem statement?
> 
> 1. Codec
> 2. Resolution
> 3. Video card
> 4. `nvidia-smi -dmon` readings

**Comment by rarzumanyan** [comment]
This is feasible but it will require small changes to the codebase.
It's possible to de-couple demuxing and decoding processes as it's shown in this sample:
https://github.com/NVIDIA/VideoProcessingFramework/blob/a935cb7847eb4d6f351500bf30e99575744a14c1/SampleDemuxDecode.py#L78-L85

I need to extend `nvc.PacketData` structure and add flag for a key frame. Since there are no inter-frame dependencies in case of key frames, decoding only them shall be possible. Although I'm now sure how much faster would it be in comparison to regular decoding.

I'll come back a bit later as I add key frame flag to `nvc.PacketData`.

**Comment by XuJing98** [comment]
Thank you very much! I'll test it soon.

**Comment by rarzumanyan** [comment]
>So I'm wondering what the reason for that is?

If you decode key frames only, Nvdec does `1 / gop_size` of the usual job, hence the near-zero usage.

>How does the demuxer work?

It extracts compressed video frames from the input. When you create a decoder from input file path and gpu id it creates a demuxer under the hood. You can also create a stand-alone demuxer like it's shown in `SampleDemuxDecode.py` or use any external process like ffmpeg in `SampleDecodeRTSP.py` to extract elementary video stream and feed it to decoder.

>Is the decoding process not totally on GPU?

Decoding is done totally on GPU.

Key frames are encoded without any other reference to other video frames, hence decoder can deal with them in a random fashion (that's BTW how seek works - it seeks to closest key frame and then decode everything in between closest key frame and the frame you're seeking for).

**Comment by XuJing98** [comment]
Thanks a lot for your reply. BTW VPF is excellent.

**Comment by XuJing98** [comment]
Hi @rarzumanyan,
Sorry, I still have questions. I used ffprobe to show the number of intra-frames(i frames) of my testing video. And I found the number of key frames that I got using VPF is less than the actual number of i frames of that testing video. So, key frame is part of i frame, is that right? Is there any flag that can detect i frame? 

Also, I found, for some small videos are composed of only 3 or 4 i frames, surface_nv12 is always empty even though ```pdata_in.key```is true. ```surface_nv12 = nvDec.DecodeSurfaceFromPacket(pdata_in, packet, pdata_out)``` So for those videos,  i got an empty torch tensor. Do you know what is the reason for that?

Thank you very much!

**Comment by rarzumanyan** [comment]
@XuJing98 

That's normal development process, don't worry )
In order to fully test the feature we need to split the testing into 2 parts:

1. Make sure all key frames are detected: amount of key frames detected by VPF is same as that by ffprobe.
2. Make sure all key frames are decoded: amount of non-empty decoded surfaces is same that in pt. 1.

Could you please check pt. 1 on one of videos you're currently have issues with?

>So, key frame is part of i frame, is that right?

I frame and key frame are synonyms.

**Comment by XuJing98** [comment]
Hi @rarzumanyan 
I've checked the pt.1 with the code shown below on some of my testing videos. 
<img width="696" alt="截屏2022-07-19 17 04 03" src="https://user-images.githubusercontent.com/53262417/179712030-3b211494-6373-4993-ad1d-1fd2826c087b.png">
I found the number of ```total```(key is 1) is the same as the number of i frames got by ffprobe. However, the number of ```surface``` (surface_nv12 is not empty) is less than the number of i frames. (if the number of key frames are 100, the number of surface would be 97) Somehow the surface_nv12 of the last three key frames are always empty.

Thank you very much!

**Comment by rarzumanyan** [comment]
@XuJing98 

>Somehow the surface_nv12 of the last three key frames are always empty.

Please make sure you're flushing decoder in the end and increasing counter by number of surfaces returned by flush.
Because `PyNvDecoder.DecodeSurfaceFromPacket` is async it has some latency to it due to internal frame queue which needs to be flushed in the end of decoding session.

**Comment by XuJing98** [comment]
You're right, my bad. Now it works fine. Thank you!

**Comment by rarzumanyan** [comment]
@XuJing98 

Thanks a lot.
Any chance you can add test to `Tests/test_PyFfmpegDemuxer.py`?

**Comment by rarzumanyan** [comment]
Closing as fixed.

**Comment by Airuio** [comment]
Hi，
> pdata_in.key

Object has no attribute ‘key’， should i compile the branch #356 to use this api?
