### ISSUE TITLE
It always return false when encoding the first three images（EncodeSurface）

### ISSUE THREAD

**Issue by Garfield2005** [NVIDIA/VideoProcessingFramework#373]
I am trying to convert a set of images into a video with VPF, my basic code is below:
```
std::shared_ptr<PyNvEncoder> encoder_ptr = std::make_shared<PyNvEncoder>(encode_options, gpuid, VPF::Pixel_Format::NV12, verbose);

std::stirng video_file = "demo.h264";
std::ofstream output_video_ofs.open(video_file, std::ios::out | std::ios::binary);

while(true)
{
    std::shared_ptr<Surface> yuv4202nv12 = ... /** data from other steps*/

    // encoding
    bool success = encoder_ptr->EncodeSurface(yuv4202nv12, packet);
    if (!success){
      std::cout << "encode failed" << std::endl;
      continue;
    }
    
    // write bytes to video file
    output_video_ofs.write(reinterpret_cast<char*>(packet.data()), packet.size());
}

// flush
while (true){
  bool success = encoder_ptr->FlushSinglePacket(packet);
  if(!success){
    break;
  }
  output_video_ofs.write(reinterpret_cast<char*>(packet.data()), packet.size());
}
output_video_ofs.close();
```

I found it always return "encoding failed" for the first three images(success is false, success is true for other images) : 
```
bool success = encoder_ptr->EncodeSurface(yuv4202nv12, packet);
```

However, the final video is correct(converting the demo.h264 to demo.mp4 with ffmpeg, I can extract the correct frames from the demo.mp4).

I want to know:
1. Why it always return false when encoding the first three images?
2. The bytes from the first three images do not written to the video file, but I can extract the images from final video

**Comment by rarzumanyan** [comment]
Hi @Garfield2005 

It happens due to following reasons:

1. Async encoder nature. Every time you kick off frame to HW, driver puts the frame into input (raw) frames queue and checks if there are any frames in output (encoded) frames queue. It is done to increase performance and reduce amount of sync calls between your application and GPU driver.
2. Encoder may have some latency due to frame reordering. For better compression efficiency video frames may be encoded in order which is different from the order you submit them to HW. This will be later taken care of by decoder (which will output frames exactly how you submitted them). It's not Nvenc - specific, googling for "B frames reordering" may be a good place to start.

>The bytes from the first three images do not written to the video file, but I can extract the images from final video

That's impossible because if encoded bytes aren't written to output file you won't be able to decode them later, right? ;)

I recommend you to take a look at `SampleMeasureVideoQuality.py` which illustrates how you can manage the encode - decode process without any intermediate file. It's written in Python but you will get the overall idea.

**Comment by Garfield2005** [comment]
@rarzumanyan 
Thanks!  

I did some tests：You are right,  Async encoder caused this phenomenon.

I have 500 input images.
If I use the following code,  EncodeSurface  will write 497 packets bytes, and FlushSinglePacket  will write 3 packet bytes.
```
bool success = encoder_ptr->EncodeSurface(yuv4202nv12, packet);
```

If I set the param sync=true,  "encode failed"  does not appeared. EncodeSurface  will write 500 packets bytes, and FlushSinglePacket write zero packet
```
bool success = encoder_ptr->EncodeSurface(yuv4202nv12, packet, true);
```



> ;)That's impossible because if encoded bytes aren't written to output file you won't be able to decode them later, right? 

yes, the encoder write all the images bytes!
