### ISSUE TITLE
Questions on context sharing and lock

### ISSUE THREAD

**Issue by kingcrimsontianyu** [NVIDIA/VideoProcessingFramework#440]
I have a few questions regarding the idiomatic use of context and lock that I hope could be answered by experts here. It turns out that [Nvidia video sdk samples](https://github.com/NVIDIA/video-sdk-samples) repository does not accept issues, so I have to post the questions here. Apology in advance, and thanks for the reply!

1. In Nvidia's codec samples, a `CUvideoctxlock `object is created via `cuvidCtxLockCreate()` per NvDecoder. For multithreaded use, should we avoid doing this, but instead create a single lock upfront in the main thread, and share it with all the instances of decoders from different threads?
2. In the sample code, the lock is created in the NvDecoder constructor, assigned to `CUVIDDECODECREATEINFO`'s field `vidLock` in the HandleVideoSequence callback, and destroyed in the destructor. But the CUDA calls in other parts of the NvDecoder are still sandwiched by `cuCtxPushCurrent` and `cuCtxPopCurrent` instead of by the lock. So is push/pop still considered thread-safe or should we replace them with the `cuvidCtxLock`/`cuvidCtxUnlock` duo? 
3. For video decoding, if we set `videoDecodeCreateInfo.ulCreationFlags = cudaVideoCreate_PreferCUVID;` (decoding is run on the NVDEC hardware), is `videoDecodeCreateInfo.vidLock` still relevant at all? Could we set it to `nullptr`?
4. As one of the CUDA designers TMurray [described in 2012](https://forums.developer.nvidia.com/t/cuda-context-and-threading/26625/6?u=king_crimson), since CUDA 4.0, a single context can be bound to multiple threads at the same time. So is the practice of guarding all CUDA calls with push/pop and lock/unlock still necessary at all today? Or is there still a compelling reason to use them here?
5. The encoding API documentation suggests that _... the client should create a floating CUDA context ..._ . Assuming that this symmetrically applies to the decoding API, would using the primary context pose any problem?

**Comment by gedoensmax** [comment]
1. Yes. You will want to share it across all threads.
2.+4. The cuvidCtxLock/Unlock is indeed a sort of work around  for the pre-cuda-4.0 mess of having to explicitly manage the context ownership between threads (it's basically a critical section + cuCtxPush/Pop helper) - in theory we should no longer need it as cuvid should have its own critical sections for the few places where it matters. 
Basically the context lock should be optional starting with CUDA 4.0 as the app could (just in theory as this is not recommended) just use cuCtxPushCurrent once on every thread that may call the decoder or cuda. We recommend ensuring to push/pop in critical section instead of once per thread.
5. This is exactly how I would do it. FFmpeg does it the same way (if `-init_hw_device cuda:0,primary_ctx=1` is used): https://github.com/FFmpeg/FFmpeg/blob/master/libavutil/hwcontext_cuda.c#L358
https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/nvenc.c#L1635-L1655
In general it is recommended to ensure a single CUDA context across your whole application. This can easily be verified using Nsight Systems if you are not sure.
