### ISSUE TITLE
Optimize GPU memory - Nvidia A100

### ISSUE THREAD

**Issue by kevinzezel** [NVIDIA/VideoProcessingFramework#482]
Hi,

How can i change these parameters to optimize memory?

CUVIDDECODECREATEINFO structure:

ulNumDecodeSurfaces 
ulNumOutputSurfaces 
DeinterlaceMode
ulIntraDecodeOnly

https://developer.nvidia.com/blog/optimizing-video-memory-usage-with-the-nvdecode-api-and-nvidia-video-codec-sdk/

My GPU Nvidia A100 is consuming 500mb of RAM in a 1080p video stream over RTSP to decode. I have a project to process 3.600 cameras. I'm trying to reduce as much memory as possible.

Regards,
Kevin

**Comment by RomanArzumanyan** [comment]
Hi @kevinzezel 
To my best knowldge, each video is decoded in it's own session and it's impossible to share resources between sessions.
If it's possible I recommend you to do 2 things:

1. Check memory consumption with SampleDecode from Video Codec SDK Samples across multiple GPUs to see the possible difference. If you see the mem consumption difference across GPUs with SampleDecode it means the different amount of memory is allocated within driver itself and not by user application.
2. Re-build VPF with `TRACK_TOKEN_ALLOCATIONS` CMake option to inspect mem allocaitons within VPF.

Also I've created a PR which reduces memory usage in VPF according to this article:
https://developer.nvidia.com/blog/optimizing-video-memory-usage-with-the-nvdecode-api-and-nvidia-video-codec-sdk/

Though HEVC already has moderate DPB size so you probably won't see much of a difference.

**Comment by RomanArzumanyan** [comment]
Hi @kevinzezel 

It's hard to tell because when decoding with Video Codec SDK, one don't allocate memory in vRAM explicitly.
Instead of that, application relies on built-in video parser which tells how much memory is needed.
I recommend you to check out latest commit from `master` branch, it now has PR merged which main aim is memory footprint reduction.

https://github.com/NVIDIA/VideoProcessingFramework/blob/d8d5d1874c65ecfe6a82db2c282182e1b865452e/src/TC/src/NvDecoder.cpp#L166-L168

So VPF will basically allocate as small amount of memory as possible + some spare space for better pipelining.
If your problem persists I assume the next place to go would be NVIDIA developers forum.

**Comment by RomanArzumanyan** [comment]
Hi @kevinzezel 

To my best knowledge, this approach isn't supported by Video Codec SDK on the API level.
One decoding session corresponds to one bitstream.

>since each stream only has 5FPS

That doesn't matter on decoder level simply because there's no such thing as FPS in video codec standards. 
You may think of video stream as list of frames and decoder as iterator over the list.
FPS, PTS, DTS and other entities exist on video container level.
