### ISSUE TITLE
RGB frames extracted with VPF are different to FFmpeg

### ISSUE THREAD

**Issue by DmitryUlyanov** [NVIDIA/VideoProcessingFramework#63]
**Describe the bug**
Hi, I want to process the video frame by frame using pytorch and I followed the example on wiki. Previously I used ffmpeg to extract frames and load them sequentially. I wanted to validate if VPF decodes frames in the same way but it turns out that there is some discrepancy in the appearance.

We are working on 3D body reconstruction so I apologize for photos in underwear but it's just the data we work with. 

Here is the frame extracted with VPF:
![00000](https://user-images.githubusercontent.com/6727524/84586945-f5d9c700-ae23-11ea-9666-25d266deec5c.jpg) 

And with FFMpeg
![00001](https://user-images.githubusercontent.com/6727524/84586930-e3f82400-ae23-11ea-9280-f3c3a6933e33.jpg)

Please find [here](https://drive.google.com/file/d/1n31O2gBqVRs4298cEIGQnaroSgM5RkSt/view?usp=sharing) the video. And [here](https://gist.github.com/DmitryUlyanov/c4a3ae09cddddc97240ce2f9978ed062) is the exact code I am running. 

**Expected behavior**
The images should be the same

**Desktop (please complete the following information):**
 - OS: Ubuntu 18
 - Nvidia driver version 440.82
 - CUDA Version 10.2
 - Video Codec SDK Version 9.1.23
 - Python Version 3.8

**Comment by rarzumanyan** [comment]
Hi @DmitryUlyanov 

>Previously I used ffmpeg to extract frames and load them sequentially
>The images should be the same

H.264 and H.265 standards support only YUV420 pixel format which means if you decode any H.264 / H.265 video with any conformant decoder, YUV420 output should be bit-to-bit same.

However, YUV420->RGB conversion isn't part of the H.264 / H.265 standard and is just a color conversion function which doesn't have to produce result bit-to-bit same to any other YUV420->RGB conversion.

So I ask you to provide following information:

- Are FFmpeg and VPF producing same YUV420 decoded frames? 

FFmpeg supports YUV420 output format as well as VPF (Nvdec uses NV12 as native format but NV12->YUV420 only differs in chroma pixels placement, so the conversion doesn't change the chroma channels intensity values). If the answer is yes (YUV420 frames are same) then this is not a bug. Otherwise I'll have to compare VPF to reference JM / HM decoders to check if it's compliant.

**Comment by rarzumanyan** [comment]
Hi @DmitryUlyanov 
Is this issue still relevant?

**Comment by DmitryUlyanov** [comment]
Hi, the issue is relevant but I don't have time to check YUV now. Thanks
for the clarification, I will look for a workaround on the color
normalization.

Best,
Dmitry

**Comment by palsol** [comment]
I have the same problem. 

I found that nv12 converts to rgb709  not sRGB:
https://github.com/NVIDIA/VideoProcessingFramework/blob/50c7f9b1480f1cb75506c8bfac06270dd649f8c2/PyNvCodec/TC/src/TasksColorCvt.cpp#L101

But when I tried converting RGB709 to linear RGB and then to sRGB it didn't help.

I used that formulas:
for RGB709 -> Linear RGB
![image](https://user-images.githubusercontent.com/10175363/98823621-66bcf380-2443-11eb-881a-f8db86a06ddd.png)
for Linear RGB -> sRGB
![image](https://user-images.githubusercontent.com/10175363/98823728-805e3b00-2443-11eb-9692-add5c02ec480.png)

**Comment by rarzumanyan** [comment]
Hello @DmitryUlyanov, @palsol 

Please check out latest `master` branch, it has bt601 and bt709 color conversions fixed.
`SampleDecodeMultiThread.py` illustrates how to use latest color conversion features.
