### ISSUE TITLE
Single GPU decoding some video

### ISSUE THREAD

**Issue by Materx** [NVIDIA/VideoProcessingFramework#64]
Hi， @rarzumanyan ：

I looked at examples:   SampleDecodeMultiThread.py, and tested our GPU(Single v100) decoding to the FPS 500.
But I want a single GPU to decode multiple videos simultaneously. 
I found that they were serial-running decoded:
one video, decode 6s   ;    two video , decode 12s
How to make a single GPU decode two or more videos in parallel?     is that  possible?

**Comment by rarzumanyan** [comment]
Hi @Materx 

To my best knowledge, this happens because of GIL.
You can run multiple sessions in parallel threads and / or sub processes but you don't see much (or any) of a performance gain. 

Please look at the similar issue here:
https://github.com/NVIDIA/VideoProcessingFramework/issues/62#issuecomment-641767610

I'm running out of depth here (don't have too much of a Python development expertise) so if you can try mentioned approach and come back as you get results that would be really great.

**Comment by Materx** [comment]
thx @rarzumanyan 
the #62 give me perfect solution!

**Comment by niaoyu** [comment]
> thx @rarzumanyan
> the #62 give me perfect solution!

@Materx Hi， I just adopt the multuprocessing method and the result is just the same as multi thread method. 
Have you achieve the improvements? could you just share the snip code for that?

**Comment by Materx** [comment]
@niaoyu sry,I have given up the research.

**Comment by niaoyu** [comment]
> @niaoyu sry,I have given up the research.

Thanks for your reply.

And I just want to know ,did you achieve idea twice improvement by using multiprocessing rather than multithread?

**Comment by Materx** [comment]
no,only multithread
